### ISSUE TITLE
Make the version number in en-minimal '0'

### ISSUE THREAD

**Issue by benjaoming** [fle-internal/content-pack-maker#31]
I'm guessing that if we put `"language_pack_version": 0` in the metadata of the minimal language pack, then updates will always show up and this issue will be solved?

https://github.com/learningequality/ka-lite/issues/5102

**Comment by benjaoming** [comment]
It seems that a `"code": "en"` is absent from `all_metadata.json` is absent, perhaps if we include English in the content pack meta data, our UI will allow to download updates?

**Comment by benjaoming** [comment]
@aronasorman my manually edited `all_metadata.json` have all been overwritten time and time again and I'm kind of tired of manually appending this information.

Would you care to weigh in here?

**Comment by benjaoming** [comment]
This is the entry that I'm adding....
```
   {
      "subtitle_count":0,
      "language_pack_version":3,
      "topic_tree_translated":100,
      "zip_size":733792710,
      "name":"English",
      "beta":false,
      "code":"en",
      "software_version":"0.16",
      "video_count":8034,
      "percent_translated":100,
      "native_name":"English"
   },
```

**Comment by benjaoming** [comment]
en-minimal's content data should read `"subtitle_count": 0` btw. because it doesn't contain subtitles.. that will make the content pack download page also say `+7208 subtitles` next to the Upgrade button :)

**Comment by aronasorman** [comment]
The english data here points to `en.zip`, not `en-minimal.zip`. This was previously set to 0 always, causing them not to update their english content pack. But I thought we wanted them to have the option to update? If so, we have to leave it to be incrementing.

**Comment by benjaoming** [comment]
metadata in en-minimal: Set the version to 0, always, so it always will prompt for an update if installed
en-zip: Use normal versioning

all_metadata: Add en metadata, currently it has none: http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/all_metadata.json.bak20160801

**Comment by benjaoming** [comment]
This issue + the fact that we distribute a broken content pack by default is IMO a great enough reason to simply stop having the minimal content pack.

Instead, for testing purposes, I suggest having something like en-test.zip and making it possible to ship an empty content.db, automatically prompting users to install content packs.
