### ISSUE TITLE
Version numbers missing in metadata.json and all_metadata.json

### ISSUE THREAD

**Issue by benjaoming** [fle-internal/content-pack-maker#34]
I'm not aware of the specifics in the build process, so this report may be a bit flawed.

After finalizing the content packs, a version number should appear in all_metadata.json, currently it seems to be just `1`.

Desired end result: When bumping version numbers, the KA Lite client UI will discover that online versions have been updated and display Upgrade buttons to users.

**Comment by benjaoming** [comment]
Instead of version numbers, consider using timestamps -- That way, it can be automated.

**Comment by benjaoming** [comment]
Now the file has been overwritten again, no warnings.

Just curious: When I create an issue here, is it read?

**Comment by benjaoming** [comment]
No one will receive language pack updates when the version in all_metadata isn't bumped.

**Comment by aronasorman** [comment]
re: read -- yeah!

I'll make the content-pack-maker automatically increment the version
numbers (or maybe follow the bamboo build number), instead of defaulting to
1.

**Comment by benjaoming** [comment]
Using Bamboo's build number would be a great start, that way we can identify the origins of the content packs much easier.
