### ISSUE TITLE
Some video nodes incorrectly flagged having no files

### ISSUE THREAD

**Issue by jamalex** [fle-internal/content-pack-maker#38]
Some videos are marked in the content database as "total_files = 0", which leads to them not being downloadable through the KA Lite interface (and some screwiness in the counts).

This is because `remote_size` is also 0 for these videos. Seems to be because `download_size` is 0, coming from KA:
https://github.com/fle-internal/content-pack-maker/blob/a941dc7e6e4a514cb1981e6092cdc675396554b5/contentpacks/khanacademy.py#L975

Affected videos, by YT ID:
zhNP1LM479g
yjU49bK1gkA
ocAAkB32Hqs
nHi-3jP6Mvc
tlAiM2QSIBg
zlP5NwdiuAU
z_KX8Xpxa-c
zS6N5EqXpCY
uYoX_Qyknao
o6zzLAhEyqo
q5sG_CkkAs8
_GiPxFvUUxs
xRGjQdHToNA
Yhaa214UKvA
u-FSLjbuv_s
BjIPqJ0paXI
ocAAkB32Hqs
nHi-3jP6Mvc

**Comment by benjaoming** [comment]
I have a similar issue with Swahili (Kiswahili), the json data is meaningless. Says that 88% is translated, 10% of topic tree, has 0 videos.

The entire content.db is empty.

```
{
   "language_pack_version":1,
   "software_version":"0.16",
   "code":"sw",
   "percent_translated":88.0184331797,
   "topic_tree_translated":10.8234036305,
   "subtitle_count":0,
   "video_count":0,
   "name":"Swahili",
   "native_name":"Kiswahili",
   "beta":true
}
```

Related issue:

https://github.com/learningequality/ka-lite/issues/5294
